---
title: "Task4 - Model Prediction"
author: "Tianming"
date: "1/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required packages
```{r}
library(stringr); 
suppressMessages(library(tm))
```

## Load ngram data
```{r}
bigram <- data.frame(readRDS("./final/en_US/dictionary_5pct/bi_words.rds"))
trigram <- data.frame(readRDS("./final/en_US/dictionary_5pct/tri_words.rds"))
quadgram <- data.frame(readRDS("./final/en_US/dictionary_5pct/quad_words.rds"))
```

  
## Match input words in 2-gram dictionary
```{r}
next_word_bigram <- function(input_split) {
  
  next_word <- as.character(head(bigram[bigram$word1 == input_split[1], ]$word2, 1))
  
  freq <- as.character(head(bigram[bigram$word1 == input_split[1], ]$n, 1))
  
  if(identical(next_word,character(0))) {
    next_word <- "it"
    freq < -0
  }
  
  next_word_list <- list(next_word, freq)
  return(next_word_list)
}
```

## Match input words in 3-gram dictionary
## if it not found, it use the 2-gram
```{r}
next_word_trigram<-function(sentence_split) {
  
  next_word <- as.character(head(trigram[trigram$word1 == input_split[1] & 
                                          trigram$word2 == input_split[2],]$word3, 1))
  
  freq <- as.character(head(trigram[trigram$word1 == input_split[1] & 
                                       trigram$word2 == input_split[2],]$n, 1))
  
  next_word_list <- list(next_word, freq)
  
  if(identical(next_word,character(0))) {
    
    next_word_list = predict_next_word(input_split[2]) # use the last one word as input for 2-gram dictionary
  
    }
  return(next_word_list)
}
```

## Match input words in 4-gram dictionary
## if it not found, it use the 3-gram
```{r}
next_word_quagram<-function(input_split) {
  
  next_word <- as.character(head(quagram[quagram$word1 == input_split[1] 
                                        & quagram$word2 == input_split[2]
                                        & quagram$word3 == input_split[3]
                                        ,]$word4,1))
  
  freq <- as.character(head(quagram[quagram$word1 == input_split[1] 
                                 & quagram$word2 == input_split[2]
                                 & quagram$word3 == input_split[3]
                                 ,]$n, 1))
  
  next_word_list<-list(next_word, freq)
  if(identical(next_word,character(0))) {
    next_word_list = predict_next_word(paste(sentence_split[2],sentence_split[3],sep=" "))
  }
  return(next_word_list)
}
```

## function for searching the input text
## this function decides which above function to use
```{r}
predict_next_word <- function(input, ngrams_dic = 0)  {
  # to lower case
  input_clean <- tolower(input)
  # remove and stop words
  input_clean <- removeWords(input_clean, stopwords("en"))
  # remove numbers and extra whitespace
  input_clean <- stripWhitespace(removeNumbers(input_clean, preserve_intra_word_dashes = TRUE))
  # split input text into single word
  input_split <- strsplit(input_clean," ")[[1]]
  # Number of effitive input words
  input_len <- length(input_split)
  
  if(input_len == 1 || ngrams_dic == 2) { ##use bigram to predict the next word
    next_word_list <- next_word_bigram(tail(input_split, 1))
  }  
  else if(input_len == 2 || ngrams_dic == 3) { ##use trigram to predict the next word
    next_word_list <- next_word_trigram(tail(input_split, 2))
  }
  else if(input_len > 2 || grams_dic == 3) {
    next_word_list <- next_word_quagram(tail(input_split, 3))
  }
  else {
    next_word_list <- list("it", 0)
  }
  return(next_word_list)
}
```

## teset
```{r}
input <- "If this isn't the cutest thing you've ever seen, then you must be"
predict_next_word(input, 2)
```

```{r}
input <- "Hey sunshine, can you follow me and make me the"
predict_next_word(input, 3)
```











